apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-next-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CyrilDesch/portfolio-next.git
    targetRevision: deploy-production
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
