apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-next
  labels:
    app: portfolio-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-next
  template:
    metadata:
      labels:
        app: portfolio-next
    spec:
      containers:
        - name: portfolio-next
          image: ghcr.io/cyrildesch/portfolio-next-example:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
