apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-next
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: portfolio.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-next
                port:
                  number: 80
